name: Converage
on: [push]
jobs:
  coverage_checking:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Check out
        uses: actions/checkout@v1
      - name: Generate coverage
        uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: ./coverage/lcov.info