name: Analyze code statically
on: 
  push:
    branch: [build/codeQuality]


jobs:
  jshint:
    runs-on: ubuntu-latest
    env:
      working-directory: ./src
    steps:
      - uses: actions/checkout@v2
      - name: Analyze code statically using JSHint
        uses: moneyforward/jshint-action@v0