name: Analyze code statically
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - build/codeQuality
  pull_request:
    branches:
      - master
jobs:
  jshint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Analyze code statically using JSHint
        uses: moneyforward/jshint-action@v0