name: Analyze code statically
on:
  push:
    branch: [build/codeQuality]
jobs:
  misspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Analyze code statically using misspell
        uses: moneyforward/misspell-action@v0
        with:
          files: |
            .
            !./.git/
            !./dist/
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Analyze code statically using ESLint
        uses: moneyforward/eslint-action@v0
        with:
          files: '.'
          options: '["--ext", ".ts"]'