
name: e2e Tests

on: [push, pull_request]

jobs:
  test:
    name: Running e2e Tests with npm
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm install
    - run: npm run compile
    - run: sudo ./node_modules/.bin/extest setup-tests -c 1.45.0
    - run: sudo chmod -R 777 ./test-resources
    - run: sudo ./node_modules/.bin/extest run-tests -u ./out/e2e-tests/*.test.js


    #- name: Slack Notification
    #  if: ${{ failure() }}
    #  uses: rtCamp/action-slack-notify@v2.0.0
    #  env:
    #    SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    #    SLACK_USERNAME: npmTestBot
    #    SLACK_TITLE: "One or more tests failed. Commit message: "