# Github action workflow that will post the results of the code coverage checker to Codecov.

name: Test Coverage checker
on: push
jobs:
    codecov: 
        name: Publish to Codecov
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v1
        -   name: Install Node.js
            uses: actions/setup-node@v1
            with:
                node-version: '10.x'
        -   run: npm install
        -   name: download and run istanbul
            run: npx nyc@15.0.1 --reporter=text --reporter=html mocha
        -   name: send to Codecov
            uses: codecov/codecov-action@v1
            with:
                token: ${{ secrets.CODECOV_TOKEN }}