on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      working-directory: ./
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 8.x
      - run: npm install
        working-directory: ./
      - name: Run tests
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: node ./out/test/runTest.js
